//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamuraiApp.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamuraiEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SamuraiEntity()
        {
            this.BattleSamurais = new HashSet<BattleSamuraiEntity>();
        }
    
        public int SamuraiId { get; set; }
        public string Picture { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Town { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattleSamuraiEntity> BattleSamurais { get; set; }
    }
}
